from django.contrib import admin
from .models import User, Product, ProductVariant, ProductImage, Category, Wishlist, Cart, CartItem, Order, OrderItem, Payment, Review, Shipping,  BlogPost, Brand, PriceRange, Size, Color, Tag

admin.site.register(Brand)
admin.site.register(PriceRange)
admin.site.register(Size)
admin.site.register(Color)
admin.site.register(Tag)
admin.site.register(BlogPost)
admin.site.register(User)
admin.site.register(Product)
admin.site.register(ProductVariant)
admin.site.register(ProductImage)
admin.site.register(Category)
admin.site.register(Wishlist)
admin.site.register(Cart)
admin.site.register(CartItem)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(Payment)
admin.site.register(Review)
admin.site.register(Shipping)